/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.udesc.br.swingtest;

import java.awt.CardLayout;

/**
 *
 * @author naira
 */
public class TesteInterface extends javax.swing.JFrame {

    private final CardLayout cardLayout;
    /**
     * Creates new form TesteInterface
     */
    public TesteInterface() {
        initComponents();
        cardLayout = new CardLayout();
        pCards.setLayout(cardLayout);
        cardLayout.addLayoutComponent(pMusicas, "musicas");
        cardLayout.addLayoutComponent(pArtistas, "artistas");
        cardLayout.addLayoutComponent(pAlbuns, "albuns");
        cardLayout.addLayoutComponent(pPlaylist, "playlist");
        mostrarTela("musicas");

    }
    private void mostrarTela(String chave){
        cardLayout.show(pCards, chave);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCards = new javax.swing.JPanel();
        pMusicas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMusicas = new javax.swing.JTable();
        pFormulario = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lDuracao = new javax.swing.JLabel();
        tfDuracao = new javax.swing.JTextField();
        lArtista = new javax.swing.JLabel();
        Artista = new javax.swing.JComboBox<>();
        lAlbum = new javax.swing.JLabel();
        Album = new javax.swing.JComboBox<>();
        btmCadastrarMusica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pArtistas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tArtistas = new javax.swing.JTable();
        pFormulario2 = new javax.swing.JPanel();
        lNome2 = new javax.swing.JLabel();
        tfNome2 = new javax.swing.JTextField();
        lGenero = new javax.swing.JLabel();
        tfGenero = new javax.swing.JTextField();
        lNascimento = new javax.swing.JLabel();
        tfNascimento = new javax.swing.JTextField();
        lCarreira = new javax.swing.JLabel();
        btmCadastrarArtista = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTituloArtistas = new javax.swing.JLabel();
        pAlbuns = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tArtistas1 = new javax.swing.JTable();
        pFormulario3 = new javax.swing.JPanel();
        lNome3 = new javax.swing.JLabel();
        tfNome3 = new javax.swing.JTextField();
        lArtista2 = new javax.swing.JLabel();
        tfArtista2 = new javax.swing.JTextField();
        lDataDeLancamento = new javax.swing.JLabel();
        tfDataDeLancamento = new javax.swing.JTextField();
        lGravadora = new javax.swing.JLabel();
        btmAdicionar = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTituloAlbum = new javax.swing.JLabel();
        pPlaylist = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tArtistas2 = new javax.swing.JTable();
        pFormulario4 = new javax.swing.JPanel();
        lNome4 = new javax.swing.JLabel();
        tfNome4 = new javax.swing.JTextField();
        lArtista3 = new javax.swing.JLabel();
        tfArtista3 = new javax.swing.JTextField();
        lDataDeLancamento1 = new javax.swing.JLabel();
        tfDataDeLancamento1 = new javax.swing.JTextField();
        lGravadora1 = new javax.swing.JLabel();
        btmAdicionar1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTituloAlbum1 = new javax.swing.JLabel();
        MenuDeAcao = new javax.swing.JToolBar();
        btnMusicas = new javax.swing.JButton();
        btnArtistas = new javax.swing.JButton();
        btnAlbuns = new javax.swing.JButton();
        btnPlaylists = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCards.setLayout(new java.awt.CardLayout());

        tMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Duração", "Artista", "Álbum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tMusicas);
        if (tMusicas.getColumnModel().getColumnCount() > 0) {
            tMusicas.getColumnModel().getColumn(1).setResizable(false);
            tMusicas.getColumnModel().getColumn(2).setResizable(false);
            tMusicas.getColumnModel().getColumn(3).setResizable(false);
            tMusicas.getColumnModel().getColumn(3).setHeaderValue("Álbum");
        }

        pFormulario.setBackground(new java.awt.Color(204, 204, 204));

        lNome.setText("Nome");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        lDuracao.setText("Duração");

        lArtista.setText("Artista ");

        Artista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lAlbum.setText("Álbum");

        Album.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btmCadastrarMusica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btmCadastrarMusica.setText("Cadastrar");
        btmCadastrarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCadastrarMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormularioLayout = new javax.swing.GroupLayout(pFormulario);
        pFormulario.setLayout(pFormularioLayout);
        pFormularioLayout.setHorizontalGroup(
            pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfDuracao)
                    .addComponent(lAlbum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Album, 0, 191, Short.MAX_VALUE)
                    .addComponent(lDuracao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lArtista, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Artista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmCadastrarMusica))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pFormularioLayout.setVerticalGroup(
            pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btmCadastrarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Cadastro de Músicas");

        javax.swing.GroupLayout pMusicasLayout = new javax.swing.GroupLayout(pMusicas);
        pMusicas.setLayout(pMusicasLayout);
        pMusicasLayout.setHorizontalGroup(
            pMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMusicasLayout.createSequentialGroup()
                .addComponent(pFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMusicasLayout.setVerticalGroup(
            pMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMusicasLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(pMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pCards.add(pMusicas, "card2");

        tArtistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Nascimento", "Carreira"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tArtistas);
        if (tArtistas.getColumnModel().getColumnCount() > 0) {
            tArtistas.getColumnModel().getColumn(1).setResizable(false);
            tArtistas.getColumnModel().getColumn(2).setResizable(false);
            tArtistas.getColumnModel().getColumn(3).setResizable(false);
        }

        pFormulario2.setBackground(new java.awt.Color(204, 204, 204));

        lNome2.setText("Nome");

        tfNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNome2ActionPerformed(evt);
            }
        });

        lGenero.setText("Gênero");

        lNascimento.setText("Nascimento");

        tfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNascimentoActionPerformed(evt);
            }
        });

        lCarreira.setText("Carreira");

        btmCadastrarArtista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btmCadastrarArtista.setText("Cadastrar");
        btmCadastrarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCadastrarArtistaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout pFormulario2Layout = new javax.swing.GroupLayout(pFormulario2);
        pFormulario2.setLayout(pFormulario2Layout);
        pFormulario2Layout.setHorizontalGroup(
            pFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormulario2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGenero)
                    .addComponent(lCarreira, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lGenero, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNome2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmCadastrarArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(tfNascimento)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pFormulario2Layout.setVerticalGroup(
            pFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormulario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lCarreira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btmCadastrarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTituloArtistas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTituloArtistas.setText("Artistas");

        javax.swing.GroupLayout pArtistasLayout = new javax.swing.GroupLayout(pArtistas);
        pArtistas.setLayout(pArtistasLayout);
        pArtistasLayout.setHorizontalGroup(
            pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistasLayout.createSequentialGroup()
                .addComponent(pFormulario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTituloArtistas)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pArtistasLayout.setVerticalGroup(
            pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloArtistas)
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pFormulario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCards.add(pArtistas, "card2");

        tArtistas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Nascimento", "Carreira"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tArtistas1);
        if (tArtistas1.getColumnModel().getColumnCount() > 0) {
            tArtistas1.getColumnModel().getColumn(1).setResizable(false);
            tArtistas1.getColumnModel().getColumn(2).setResizable(false);
            tArtistas1.getColumnModel().getColumn(3).setResizable(false);
        }

        pFormulario3.setBackground(new java.awt.Color(204, 204, 204));

        lNome3.setText("Nome");

        tfNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNome3ActionPerformed(evt);
            }
        });

        lArtista2.setText("Artista");

        lDataDeLancamento.setText("Data de Lançamento");

        tfDataDeLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataDeLancamentoActionPerformed(evt);
            }
        });

        lGravadora.setText("Gravadora");

        btmAdicionar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btmAdicionar.setText("Adicionar");
        btmAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAdicionarActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        javax.swing.GroupLayout pFormulario3Layout = new javax.swing.GroupLayout(pFormulario3);
        pFormulario3.setLayout(pFormulario3Layout);
        pFormulario3Layout.setHorizontalGroup(
            pFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormulario3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfArtista2)
                    .addComponent(lGravadora, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lArtista2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNome3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDataDeLancamento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(tfDataDeLancamento)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pFormulario3Layout.setVerticalGroup(
            pFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormulario3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNome3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lArtista2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfArtista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDataDeLancamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDataDeLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lGravadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btmAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTituloAlbum.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTituloAlbum.setText("Álbum");

        javax.swing.GroupLayout pAlbunsLayout = new javax.swing.GroupLayout(pAlbuns);
        pAlbuns.setLayout(pAlbunsLayout);
        pAlbunsLayout.setHorizontalGroup(
            pAlbunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbunsLayout.createSequentialGroup()
                .addComponent(pFormulario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pAlbunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTituloAlbum)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pAlbunsLayout.setVerticalGroup(
            pAlbunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlbunsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloAlbum)
                .addGap(18, 18, 18)
                .addGroup(pAlbunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pFormulario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCards.add(pAlbuns, "card2");

        tArtistas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Nascimento", "Carreira"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tArtistas2);
        if (tArtistas2.getColumnModel().getColumnCount() > 0) {
            tArtistas2.getColumnModel().getColumn(1).setResizable(false);
            tArtistas2.getColumnModel().getColumn(2).setResizable(false);
            tArtistas2.getColumnModel().getColumn(3).setResizable(false);
        }

        pFormulario4.setBackground(new java.awt.Color(204, 204, 204));

        lNome4.setText("Nome");

        tfNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNome4ActionPerformed(evt);
            }
        });

        lArtista3.setText("Artista");

        lDataDeLancamento1.setText("Data de Lançamento");

        tfDataDeLancamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataDeLancamento1ActionPerformed(evt);
            }
        });

        lGravadora1.setText("Gravadora");

        btmAdicionar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btmAdicionar1.setText("Adicionar");
        btmAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAdicionar1ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane7.setViewportView(jTextArea3);

        javax.swing.GroupLayout pFormulario4Layout = new javax.swing.GroupLayout(pFormulario4);
        pFormulario4.setLayout(pFormulario4Layout);
        pFormulario4Layout.setHorizontalGroup(
            pFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormulario4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfArtista3)
                    .addComponent(lGravadora1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lArtista3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNome4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDataDeLancamento1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmAdicionar1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(tfDataDeLancamento1)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pFormulario4Layout.setVerticalGroup(
            pFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormulario4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNome4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lArtista3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfArtista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDataDeLancamento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDataDeLancamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lGravadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btmAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTituloAlbum1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTituloAlbum1.setText("Playlists");

        javax.swing.GroupLayout pPlaylistLayout = new javax.swing.GroupLayout(pPlaylist);
        pPlaylist.setLayout(pPlaylistLayout);
        pPlaylistLayout.setHorizontalGroup(
            pPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlaylistLayout.createSequentialGroup()
                .addComponent(pFormulario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTituloAlbum1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pPlaylistLayout.setVerticalGroup(
            pPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloAlbum1)
                .addGap(18, 18, 18)
                .addGroup(pPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pFormulario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCards.add(pPlaylist, "card2");

        MenuDeAcao.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MenuDeAcao.setRollover(true);

        btnMusicas.setText("Músicas");
        btnMusicas.setFocusable(false);
        btnMusicas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMusicas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicarMusicas(evt);
            }
        });
        MenuDeAcao.add(btnMusicas);

        btnArtistas.setText("Artistas");
        btnArtistas.setFocusable(false);
        btnArtistas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArtistas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicarArtistas(evt);
            }
        });
        MenuDeAcao.add(btnArtistas);

        btnAlbuns.setText("Álbuns");
        btnAlbuns.setFocusable(false);
        btnAlbuns.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlbuns.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlbuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicarAlbuns(evt);
            }
        });
        MenuDeAcao.add(btnAlbuns);

        btnPlaylists.setText("Playlists");
        btnPlaylists.setFocusable(false);
        btnPlaylists.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlaylists.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicarPlaylists(evt);
            }
        });
        MenuDeAcao.add(btnPlaylists);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuDeAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pCards, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(MenuDeAcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btmCadastrarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCadastrarMusicaActionPerformed

        
        
    }//GEN-LAST:event_btmCadastrarMusicaActionPerformed

    private void tfNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNome2ActionPerformed

    private void btmCadastrarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCadastrarArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmCadastrarArtistaActionPerformed

    private void tfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNascimentoActionPerformed

    private void tfNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNome3ActionPerformed

    private void tfDataDeLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataDeLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataDeLancamentoActionPerformed

    private void btmAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmAdicionarActionPerformed

    private void tfNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNome4ActionPerformed

    private void tfDataDeLancamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataDeLancamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataDeLancamento1ActionPerformed

    private void btmAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAdicionar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmAdicionar1ActionPerformed

    private void clicarMusicas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicarMusicas
        mostrarTela("musicas");

    }//GEN-LAST:event_clicarMusicas

    private void clicarArtistas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicarArtistas
        mostrarTela("artistas");

    }//GEN-LAST:event_clicarArtistas

    private void clicarAlbuns(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicarAlbuns
        mostrarTela("albuns");

    }//GEN-LAST:event_clicarAlbuns

    private void clicarPlaylists(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicarPlaylists
        mostrarTela("playlist");
    }//GEN-LAST:event_clicarPlaylists

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Album;
    private javax.swing.JComboBox<String> Artista;
    private javax.swing.JToolBar MenuDeAcao;
    private javax.swing.JTextField btmAdicionar;
    private javax.swing.JTextField btmAdicionar1;
    private javax.swing.JTextField btmCadastrarArtista;
    private javax.swing.JTextField btmCadastrarMusica;
    private javax.swing.JButton btnAlbuns;
    private javax.swing.JButton btnArtistas;
    private javax.swing.JButton btnMusicas;
    private javax.swing.JButton btnPlaylists;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel jTituloAlbum;
    private javax.swing.JLabel jTituloAlbum1;
    private javax.swing.JLabel jTituloArtistas;
    private javax.swing.JLabel lAlbum;
    private javax.swing.JLabel lArtista;
    private javax.swing.JLabel lArtista2;
    private javax.swing.JLabel lArtista3;
    private javax.swing.JLabel lCarreira;
    private javax.swing.JLabel lDataDeLancamento;
    private javax.swing.JLabel lDataDeLancamento1;
    private javax.swing.JLabel lDuracao;
    private javax.swing.JLabel lGenero;
    private javax.swing.JLabel lGravadora;
    private javax.swing.JLabel lGravadora1;
    private javax.swing.JLabel lNascimento;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNome2;
    private javax.swing.JLabel lNome3;
    private javax.swing.JLabel lNome4;
    private javax.swing.JPanel pAlbuns;
    private javax.swing.JPanel pArtistas;
    private javax.swing.JPanel pCards;
    private javax.swing.JPanel pFormulario;
    private javax.swing.JPanel pFormulario2;
    private javax.swing.JPanel pFormulario3;
    private javax.swing.JPanel pFormulario4;
    private javax.swing.JPanel pMusicas;
    private javax.swing.JPanel pPlaylist;
    private javax.swing.JTable tArtistas;
    private javax.swing.JTable tArtistas1;
    private javax.swing.JTable tArtistas2;
    private javax.swing.JTable tMusicas;
    private javax.swing.JTextField tfArtista2;
    private javax.swing.JTextField tfArtista3;
    private javax.swing.JTextField tfDataDeLancamento;
    private javax.swing.JTextField tfDataDeLancamento1;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfNascimento;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNome2;
    private javax.swing.JTextField tfNome3;
    private javax.swing.JTextField tfNome4;
    // End of variables declaration//GEN-END:variables
}
