/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.udesc.br.projeto;;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author mattheus
 */
public class TelaAlbuns extends javax.swing.JFrame {

    /**
     * Creates new form TelaPerfil
     */
    public TelaAlbuns() {
        initComponents();
        int tipoConta = buscaDadosConta();
        if(tipoConta == 1){
            btnCadastrarAlbum.setVisible(true);
            btnDesfavoritar.setVisible(false);
            btnFavoritar.setVisible(false);
            cbAlbuns.setVisible(false);
        } else {
            btnCadastrarAlbum.setVisible(false);
            btnDesfavoritar.setVisible(true);
            btnFavoritar.setVisible(true);
            cbAlbuns.setVisible(true);
        }
        inicializarListaAlbum();
    }
    
    public void inicializarListaAlbum(){
        ArrayList<Album> albuns = TelaCadastrarAlbum.getAlbuns();
        for(Album a: albuns){
            listAlbuns.append(a.toString()+"\n");
            cbAlbuns.addItem(a);
        }
    }
    
        
    private static ArrayList<Album> albunsFav = new ArrayList();
        
    public static ArrayList<Album> getAlbunsFav(){
        
        return albunsFav;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadastrarAlbum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAlbuns = new javax.swing.JTextArea();
        btnFavoritar = new javax.swing.JButton();
        btnDesfavoritar = new javax.swing.JButton();
        cbAlbuns = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Álbuns");

        btnCadastrarAlbum.setText(" Cadastrar Álbum");
        btnCadastrarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlbumActionPerformed(evt);
            }
        });

        listAlbuns.setEditable(false);
        listAlbuns.setColumns(20);
        listAlbuns.setRows(5);
        jScrollPane1.setViewportView(listAlbuns);

        btnFavoritar.setText("Favoritar Álbum");
        btnFavoritar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritarActionPerformed(evt);
            }
        });

        btnDesfavoritar.setText("Retirar dos favoritos");
        btnDesfavoritar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfavoritarActionPerformed(evt);
            }
        });

        cbAlbuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlbunsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAlbuns, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCadastrarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 53, Short.MAX_VALUE)))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDesfavoritar)
                                    .addComponent(btnFavoritar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbAlbuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFavoritar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfavoritar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarAlbum))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        btnCadastrarAlbum.getAccessibleContext().setAccessibleName("Cadastrar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlbumActionPerformed
        TelaCadastrarAlbum telaCadastrarAlbum = new TelaCadastrarAlbum();
        telaCadastrarAlbum.setVisible(true);
    }//GEN-LAST:event_btnCadastrarAlbumActionPerformed

    private void btnFavoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritarActionPerformed
        favoritarMusicas();
    }//GEN-LAST:event_btnFavoritarActionPerformed

    private void btnDesfavoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfavoritarActionPerformed
        desfavoritarMusicas();
    }//GEN-LAST:event_btnDesfavoritarActionPerformed

    private void cbAlbunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlbunsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlbunsActionPerformed
        public void favoritarMusicas(){
        // Configura o modo de seleção da lista
        
        Album albumSelecionado = (Album) cbAlbuns.getSelectedItem(); //retorna um Object. Convertemos por meio de Casting.
        //Favoritar a música
        TelaCadastrarAlbum.favoritarAlbum(albumSelecionado);
        
        albunsFav.add(albumSelecionado);
        //Exibir uma msg
        exibirMensagem("Álbum favoritado com sucesso");   
    }
    
    public void desfavoritarMusicas(){
        // Configura o modo de seleção da lista
        
        Album albumSelecionado = (Album) cbAlbuns.getSelectedItem(); //retorna um Object. Convertemos por meio de Casting.
        //Favoritar a música
        TelaCadastrarAlbum.desfavoritarAlbum(albumSelecionado);
        
        albunsFav.add(albumSelecionado);
        //Exibir uma msg
        exibirMensagem("Música retirada dos favoritos com sucesso");   
    }
    
    
    public int buscaDadosConta(){
        int tipoConta = 0;
        ArrayList<Conta> contas = TelaCadastrarConta.getContas();
        for(Conta a: contas){
            tipoConta = a.getTipoConta();
        }
        return tipoConta;
    }
    
    public void exibirMensagem(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlbuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlbuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlbuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlbuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlbuns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAlbum;
    private javax.swing.JButton btnDesfavoritar;
    private javax.swing.JButton btnFavoritar;
    private javax.swing.JComboBox<Album> cbAlbuns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listAlbuns;
    // End of variables declaration//GEN-END:variables
}
